# Generated by Django 6.0.5 on 2026-06-02 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_inspectionsite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.province'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='zone_name',
            field=models.CharField(max_length=255),
        ),
    ]
