# Generated by Django 6.0.2 on 2026-06-04 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_zone_province_alter_zone_zone_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_target', models.PositiveIntegerField(default=0)),
                ('no_of_target_done', models.PositiveIntegerField(default=0)),
                ('target_date', models.DateField()),
                ('target_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_approved_count', models.PositiveIntegerField(default=0)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.district')),
                ('division', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.division')),
                ('province', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.province')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_targets_supervisor', to=settings.AUTH_USER_MODEL)),
                ('surveyor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_targets_surveyor', to=settings.AUTH_USER_MODEL)),
                ('tehsil', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.tehsil')),
                ('zone', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.zone')),
            ],
        ),
        migrations.CreateModel(
            name='TPV01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_visit', models.DateField()),
                ('plant_location', models.CharField(blank=True, max_length=255, null=True)),
                ('phase', models.CharField(choices=[('Phase I', 'Phase I'), ('Phase II', 'Phase II'), ('Phase III', 'Phase III')], max_length=50)),
                ('inspector_name', models.CharField(max_length=255)),
                ('contractor_rep_present', models.BooleanField(default=False)),
                ('operator_caretaker_present', models.BooleanField(default=False)),
                ('gps_app_entry', models.BooleanField(default=False)),
                ('plant_type', models.CharField(choices=[('RO', 'RO'), ('UF', 'UF'), ('Media Filtration', 'Media Filtration'), ('Other', 'Other')], max_length=50)),
                ('plant_type_other', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.CharField(choices=[('500 LPH', '500 LPH'), ('1000 LPH', '1000 LPH'), ('2000 LPH', '2000 LPH'), ('4000 LPH', '4000 LPH')], max_length=50)),
                ('operating_at_visit', models.BooleanField(default=False)),
                ('water_available_to_public', models.BooleanField(default=False)),
                ('overall_status', models.CharField(choices=[('Functional', 'Functional'), ('Functional with Minor Issues', 'Functional with Minor Issues'), ('Partially Functional', 'Partially Functional'), ('Non-Functional', 'Non-Functional'), ('Not Accessible', 'Not Accessible')], max_length=100)),
                ('physical_checks', models.JSONField(blank=True, default=list)),
                ('record_checks', models.JSONField(blank=True, default=list)),
                ('service_delivery', models.CharField(blank=True, max_length=50, null=True)),
                ('om_compliance', models.CharField(blank=True, max_length=50, null=True)),
                ('recommendation', models.CharField(choices=[('Acceptable', 'Acceptable'), ('Acceptable with Observations', 'Acceptable with Observations'), ('Corrective Action Required', 'Corrective Action Required'), ('Serious Deficiency / Revisit Required', 'Serious Deficiency / Revisit Required')], max_length=100)),
                ('major_observations', models.TextField(blank=True, null=True)),
                ('inspector_signature', models.TextField(blank=True, null=True)),
                ('site_representative_signature', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpv01_records', to='api.district')),
                ('inspection_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpv01_records', to='api.inspectionsite')),
                ('tehsil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpv01_records', to='api.tehsil')),
            ],
        ),
    ]
