# Generated by Django 6.0.5 on 2026-06-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_tpv01_plant_location_remove_tpv01_plant_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionsite',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inspectionsite',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
    ]
