# Generated by Django 6.0.5 on 2026-06-09 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_boqbill_capacity_remove_boqbill_division_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boq',
            name='parent_item',
        ),
        migrations.RemoveField(
            model_name='boqbill',
            name='pst_amount',
        ),
        migrations.RemoveField(
            model_name='boqbill',
            name='pst_percent',
        ),
        migrations.RemoveField(
            model_name='boqbill',
            name='total_construction_cost',
        ),
        migrations.RemoveField(
            model_name='boqbill',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='boq',
            name='mrs_ref_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='boqbill',
            name='amount_rs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='boqbill',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='boqbill',
            name='unit_rate_rs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='boq',
            name='amount_rs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='boq',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.boqbill'),
        ),
        migrations.AlterField(
            model_name='boq',
            name='item_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='boq',
            name='rate_rs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
