# Generated by Django 6.0.5 on 2026-06-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_myuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionsite',
            name='contract_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inspectionsite',
            name='phase',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionsite',
            name='category',
            field=models.CharField(choices=[('Revamped', 'Revamped'), ('New', 'New'), ('Old', 'Old'), ('Functional', 'Functional'), ('Dysfunctional', 'Dysfunctional'), ('Not functional', 'Not functional'), ('Abondoned', 'Abondoned')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inspectionsite',
            name='type',
            field=models.CharField(choices=[('RO', 'RO'), ('UF', 'UF'), ('MF', 'MF'), ('PF', 'PF')], max_length=10),
        ),
    ]
