# Generated by Django 6.0.5 on 2026-06-18 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_contract_district_contract_division_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boq',
            old_name='amount_rs',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='boq',
            old_name='item_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='boq',
            old_name='rate_rs',
            new_name='unit_rate',
        ),
        migrations.AddField(
            model_name='boq',
            name='bill_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='boq',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.contract'),
        ),
        migrations.CreateModel(
            name='BOQInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspected_unit', models.CharField(max_length=50)),
                ('inspected_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('inspected_unit_rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('inspected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('boq', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forInspection', to='api.boq')),
            ],
        ),
    ]
