# Generated by Django 6.0.5 on 2026-06-18 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_amount_rs_boq_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boq',
            name='bill',
        ),
    ]
