# Generated by Django 6.0.5 on 2026-06-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_boq_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boq',
            name='item_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
