# Generated by Django 6.0.5 on 2026-06-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_boq_item_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='boqinspection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
