# Generated by Django 6.0.5 on 2026-06-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_boqinspection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='boqinspection',
            name='submitted_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
