# Generated by Django 6.0.5 on 2026-06-30 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_boqinspection_submitted_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boqinspection',
            old_name='inspected_unit',
            new_name='inspected_claimed_quantity',
        ),
        migrations.AddField(
            model_name='boqinspection',
            name='site',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspectionSite', to='api.inspectionsite'),
        ),
    ]
