# Generated by Django 6.0.5 on 2026-07-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_inspected_unit_boqinspection_inspected_claimed_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boq',
            name='bill_no_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
