# Generated by Django 6.0.5 on 2026-06-02 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('type', models.CharField(choices=[('RO', 'RO'), ('UF', 'UF')], max_length=10)),
                ('category', models.CharField(choices=[('Revamped', 'Revamped'), ('New', 'New'), ('Old', 'Old')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='api.district')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='api.division')),
                ('tehsil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='api.tehsil')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='api.zone')),
            ],
        ),
    ]
