# Generated by Django 6.0.5 on 2026-06-04 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_targetsurvey_tpv01'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpv01',
            name='plant_location',
        ),
        migrations.RemoveField(
            model_name='tpv01',
            name='plant_type',
        ),
        migrations.RemoveField(
            model_name='tpv01',
            name='plant_type_other',
        ),
        migrations.AddField(
            model_name='tpv01',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tpv01_inspections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inspectionsite',
            name='type',
            field=models.CharField(choices=[('RO', 'RO'), ('UF', 'UF'), ('MF', 'MF')], max_length=10),
        ),
    ]
