# Generated by Django 6.0.5 on 2026-06-08 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_inspectionsite_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.PositiveIntegerField(blank=True, null=True)),
                ('item_description', models.TextField()),
                ('unit', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate_rs', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_rs', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boq_items', to='api.district')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boq_items', to='api.division')),
                ('inspection_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boq_items', to='api.inspectionsite')),
                ('tehsil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boq_items', to='api.tehsil')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boq_items', to='api.zone')),
            ],
        ),
    ]
