# Generated by Django 6.0.5 on 2026-06-08 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_boq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boq',
            name='district',
        ),
        migrations.RemoveField(
            model_name='boq',
            name='division',
        ),
        migrations.RemoveField(
            model_name='boq',
            name='inspection_site',
        ),
        migrations.RemoveField(
            model_name='boq',
            name='tehsil',
        ),
        migrations.RemoveField(
            model_name='boq',
            name='zone',
        ),
        migrations.AddField(
            model_name='boq',
            name='parent_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='api.boq'),
        ),
        migrations.CreateModel(
            name='BOQBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_title', models.CharField(max_length=255)),
                ('bill_no', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boq_bills', to='api.inspectionsite')),
            ],
        ),
        migrations.AddField(
            model_name='boq',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.boqbill'),
        ),
    ]
