# Generated by Django 6.0.5 on 2026-06-08 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_boq_district_remove_boq_division_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boqbill',
            name='inspection_site',
        ),
        migrations.AddField(
            model_name='boqbill',
            name='capacity',
            field=models.CharField(blank=True, choices=[('500 LPH', '500 LPH'), ('1000 LPH', '1000 LPH'), ('2000 LPH', '2000 LPH'), ('4000 LPH', '4000 LPH')], default='500 LPH', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='boqbill',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.division'),
        ),
        migrations.AddField(
            model_name='boqbill',
            name='plant_type',
            field=models.CharField(blank=True, choices=[('RO', 'RO'), ('UF', 'UF'), ('MF', 'MF')], default='RO', max_length=20, null=True),
        ),
    ]
