# Generated by Django 6.0.5 on 2026-06-08 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_boqbill_inspection_site_boqbill_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boqbill',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='boqbill',
            name='division',
        ),
        migrations.RemoveField(
            model_name='boqbill',
            name='plant_type',
        ),
        migrations.AddField(
            model_name='boqbill',
            name='inspection_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boq_bills', to='api.inspectionsite'),
        ),
        migrations.AddField(
            model_name='boqbill',
            name='pst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='boqbill',
            name='pst_percent',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
        migrations.AddField(
            model_name='boqbill',
            name='total_construction_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='boqbill',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
