# Generated by Django 6.0.5 on 2026-06-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_boq_parent_item_remove_boqbill_pst_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('contractor', 'Contractor'), ('inspector', 'Inspector')], default='surveyor', max_length=20),
        ),
    ]
