# Generated by Django 6.0.5 on 2026-06-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_inspectionsite_contract_no_inspectionsite_phase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionsite',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionsite',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
    ]
