# Generated by Django 6.0.5 on 2026-06-12 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_inspectionsite_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boqbill',
            name='inspection_site',
        ),
        migrations.RemoveField(
            model_name='inspectionsite',
            name='contract_no',
        ),
        migrations.RemoveField(
            model_name='inspectionsite',
            name='district',
        ),
        migrations.RemoveField(
            model_name='inspectionsite',
            name='division',
        ),
        migrations.RemoveField(
            model_name='inspectionsite',
            name='tehsil',
        ),
        migrations.RemoveField(
            model_name='inspectionsite',
            name='zone',
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_no', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='api.district')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='api.division')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='api.province')),
                ('tehsil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='api.tehsil')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='api.zone')),
            ],
        ),
        migrations.AddField(
            model_name='boqbill',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boq_bills', to='api.contract'),
        ),
        migrations.AddField(
            model_name='inspectionsite',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='api.contract'),
        ),
    ]
