# Generated by Django 6.0.5 on 2026-06-12 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_boqbill_inspection_site_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='district',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='division',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='province',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='tehsil',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='zone',
        ),
        migrations.AddField(
            model_name='inspectionsite',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='api.district'),
        ),
        migrations.AddField(
            model_name='inspectionsite',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='api.division'),
        ),
        migrations.AddField(
            model_name='inspectionsite',
            name='tehsil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='api.tehsil'),
        ),
        migrations.AddField(
            model_name='inspectionsite',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='api.zone'),
        ),
    ]
