# Generated by Django 6.0.5 on 2026-06-18 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_contract_district_remove_contract_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='api.district'),
        ),
        migrations.AddField(
            model_name='contract',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='api.division'),
        ),
        migrations.AddField(
            model_name='contract',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='api.province'),
        ),
        migrations.AddField(
            model_name='contract',
            name='tehsil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='api.tehsil'),
        ),
        migrations.AddField(
            model_name='contract',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='api.zone'),
        ),
    ]
